<div class="col-xs-12 homeDiv">
<h2>Home - o restoranu</h2>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce convallis velit non ipsum volutpat pharetra. Donec viverra ullamcorper sem pulvinar facilisis. Nullam ac justo consectetur, commodo est non, dignissim urna. Nullam ultrices pellentesque aliquet. Nunc euismod vel eros id blandit. Etiam facilisis velit non sem facilisis varius. Phasellus nulla leo, convallis vel ex vitae, pretium egestas dolor. Duis ex risus, dignissim ac orci quis, blandit viverra enim. Proin suscipit tortor id lorem gravida scelerisque. Donec consequat, est et volutpat dictum, quam elit tempor risus, in mollis mauris urna quis risus. Aenean porta rutrum enim non feugiat.

Aliquam ante massa, vestibulum sed elementum in, tempor id diam. Sed sit amet suscipit neque. Proin arcu lectus, commodo ac dapibus a, ultrices sed lorem. Pellentesque iaculis, dui eget convallis elementum, sem metus consectetur odio, ac vestibulum urna felis et sem. Integer in tincidunt tortor, eget varius nibh. Aenean pretium ullamcorper magna ultrices consectetur. Aliquam ultrices dolor et elit eleifend, ac condimentum est tempus. Aliquam pellentesque tellus non blandit posuere. Nulla interdum varius mattis. Pellentesque volutpat non ex ultricies dignissim. Vestibulum accumsan massa vel sollicitudin pellentesque. Duis nec diam pharetra, congue metus non, pulvinar sem. Nam tincidunt metus id sapien porttitor consequat. Quisque interdum vehicula lacinia. Vivamus laoreet erat justo, quis aliquet metus fermentum commodo. Vivamus tincidunt, ex a lacinia eleifend, nibh orci sagittis mauris, et varius nisi libero eu diam.

Nullam convallis auctor nisl, ac pulvinar sem varius vel. Donec euismod fringilla laoreet. Vestibulum egestas molestie tempor. Integer egestas hendrerit magna eget convallis. Nunc porttitor imperdiet turpis, ac condimentum metus faucibus eget. Quisque faucibus felis aliquet accumsan iaculis. Nullam vitae tempus felis, eget cursus neque. Vestibulum in rhoncus enim, eu blandit tortor. Sed quis lorem est. Sed auctor tellus fermentum, pretium tellus et, posuere magna. Nunc scelerisque sit amet diam a interdum. Ut at magna quis diam sagittis ullamcorper vel sed nulla. Suspendisse et finibus nunc. Nunc laoreet volutpat mauris, in placerat quam porta in. Nullam eget dolor rutrum, pellentesque est sit amet, faucibus massa. Sed non vulputate risus, at elementum justo.


</div>